name: hospital_management_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  carousel_slider: ^3.0.0
  font_awesome_flutter: ^9.0.0
  bottom_navy_bar: ^6.0.0
  dropdownfield: ^1.0.3
  http: ^0.13.1
  fluttertoast: ^8.0.3
  dotted_line: ^3.0.0
  flutter_staggered_grid_view:
  flutter_sparkline: ^0.1.0
  animated_text_kit: ^4.1.1
  new_gradient_app_bar: ^0.1.5
  dot_pagination_swiper: ^0.1.1
  folding_cell: ^1.0.0
  transition: ^2.0.1
  charts_painter: ^1.0.0
  syncfusion_flutter_charts: ^19.1.56
  table_calendar: ^3.0.0
  image_picker: ^0.6.0
  file_picker: ^1.9.0+1
  dio: ^4.0.0
  path: ^1.6.4
  flutter_snake_navigationbar: ^0.5.0
  hive: ^2.0.4
  path_provider: ^2.0.2
  hive_flutter: ^1.0.0
  intl: ^0.17.0
  razorpay_flutter: ^1.2.6
  toast: ^0.1.5
  flutter_cached_pdfview: ^0.4.0-nullsafety
  url_launcher: ^6.0.6





dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/

  fonts:
  - family: Pacifico
    fonts:
    - asset: fonts/Pacifico-Regular.ttf
  - family: Kumbh Sans
    fonts:
    - asset: fonts/KumbhSans-Bold.ttf
  - family: Kumbh Sans-Regular
    fonts:
    - asset: fonts/KumbhSans-Regular.ttf
  - family: Quicksand-VariableFont_wght
    fonts:
    - asset: fonts/Quicksand-VariableFont_wght.ttf



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
